#服务器端口配置
server:
  port: 8081

#数据库连接配置
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.15.124:1523/mestest.xinya.com
    username: system
    password: 1

#日志配置
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    com.xydz.suppliermateriallabelprintingtool.mapper: debug

