#服务器端口配置
server:
  port: 18990

#数据库连接配置
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: system
    password: 1

#日志配置
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#logging:
#  level:
#    com.xydz.suppliermateriallabelprintingtool.mapper: debug

logging:
  file:
    path: log/
  level:
    com.xydz.suppliermateriallabelprintingtool.mapper: debug


#slf4j:
#  appender:
#    FILE: org.apache.slf4j.DailyRollingFileAppender







