#服务器端口配置
server:
  port: 18990

#数据库连接配置
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.15.124:1523/mestest.xinya.com
    username: system
    password: 1
  redis:
    host: localhost
    port: 10110
    password: zcd123

#日志配置
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#logging:
#  level:
#    com.xydz.suppliermateriallabelprintingtool.mapper: debug

logging:
  file:
    path: log/
  level:
    com.xydz.suppliermateriallabelprintingtool.mapper: debug
    root: warn


#slf4j:
#  appender:
#    FILE: org.apache.slf4j.DailyRollingFileAppender


##分页插件
#pagehelper:
#  helper-dialect: oracle
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql



